### ISSUE TITLE
Textures do not load properly

### ISSUE THREAD

**Issue by Leerandir549** [rbray89/DynamicTextureLoader#5]
Hello all! I'm having a bit of a problem when I load the game using Dynamic Texture Loader. I would like to use this mod so that I can use B9 Aerospace but it's causing a bit of a problem. I will get into the VAB or SPH and none of the textures will be loaded for the parts. I have tried re-downloading and re-installing the mod AND game but nothing has worked. Attached are screenshots and the most current  .log file. 

Thanks for the help!
-Lee
![screen shot 2016-03-28 at 12 08 15 am](https://cloud.githubusercontent.com/assets/18109904/14071400/dbbfb2de-f479-11e5-9eb0-55e902506908.png)
![screen shot 2016-03-28 at 12 10 56 am](https://cloud.githubusercontent.com/assets/18109904/14071401/dbd89aec-f479-11e5-9c15-c9027b1743e2.png)
![screen shot 2016-03-28 at 12 11 46 am](https://cloud.githubusercontent.com/assets/18109904/14071402/dbf0bf6e-f479-11e5-948d-57cdb70a9e9f.png)
![screen shot 2016-03-28 at 12 11 56 am](https://cloud.githubusercontent.com/assets/18109904/14071403/dc099d9a-f479-11e5-83e3-10ff877c9f2e.png)
![screen shot 2016-03-28 at 12 12 12 am](https://cloud.githubusercontent.com/assets/18109904/14071404/dc0f3142-f479-11e5-9d7e-1dd14943efed.png)
![screen shot 2016-03-28 at 12 12 28 am](https://cloud.githubusercontent.com/assets/18109904/14071399/db95d806-f479-11e5-8ccd-6f536f792a5b.png)
[KSP.log.zip](https://github.com/rbray89/DynamicTextureLoader/files/191394/KSP.log.zip)

**Comment by rbray89** [comment]
This is as expected. The full texture will be loaded once a part is used.

**Comment by Leerandir549** [comment]
So... With some parts, how am I supposed to know which parts they are? Especially new mods?

**Comment by rbray89** [comment]
Name and picture. This is what ATM does. If it loaded the textures for all parts in the preview window, it would take several seconds to change between part pages.
